### PR TITLE
Decoded Rig.hpp properties

### PR DESCRIPTION
**Pull request by Mozz3d**
Replaces the `unk40` placeholder and adds `boneParentIndexes` and `boneTransforms` properties at offsets 0x40 and 0x48 respectively. Which have been confirmed through testing.

### CODE REVIEW

**Review by WopsS — CHANGES_REQUESTED** [review]
Thanks for the PR :)

This file will be overwritten when every time we dump the types. You can move it out of the "Generated" directory and it should be fine, like we did for others (https://github.com/WopsS/RED4ext.SDK/tree/master/include/RED4ext/Scripting/Natives).

**Comment by poirierlouis** [comment]
I'm wondering, should it be defined here, without redscript declaration... Or better be in Codeware, as it already provides such kind of native extensions?
FYI @psiberx

**Comment by psiberx** [comment]
It should be in SDK but not in Generated.

**Comment by Mozz3d** [comment]
> Thanks for the PR :)
> 
> This file will be overwritten when every time we dump the types. You can move it out of the "Generated" directory and it should be fine, like we did for others (https://github.com/WopsS/RED4ext.SDK/tree/master/include/RED4ext/Scripting/Natives).

I moved it to Natives, I hope that's alright!

**Comment by psiberx** [comment]
Look at how other files are handled.
1. Remove generated comments.
2. Add generated stub that includes your manual override.

**Comment by Mozz3d** [comment]
Is this better? I've never really _used_ github for anything besides viewing code so you'll have to excuse me if it's a little messy. Trying my best to figure it ou.

**Comment by psiberx** [comment]
`Scripting/Natives/Generated/anim/Rig.hpp` should include your overridden header. Look at `Scripting/Natives/Generated/ink/Layer.hpp` as an example.  You can generate it by running `GameReflection::Dump()` again, but for a single file it's easier to create it manually.

**Comment by Mozz3d** [comment]
A little late, but here are the requested changes along with some further decoded properties.

**Comment by WopsS** [comment]
You also have to update the `Reflection-inl` file to exclude it from being generated in the future.

See https://github.com/WopsS/RED4ext.SDK/pull/121/files#diff-859ef96671f9a21f801808df16274cd12c0711860ddf5e6787fa521a088fae06L310.

**Comment by Mozz3d** [comment]
Is that okay? Also thank you for helping me help this project :3

**Comment by psiberx** [comment]
It should be placed at `include/RED4ext/Scripting/Natives/animRig.hpp` to exclude from being generated and keep existing includes valid (no manual override in `Reflection-inl` is needed).

**Comment by Mozz3d** [comment]
Let me know if I need to adjust anything else.

**Review by WopsS — APPROVED** [review]
Thanks for the changes! :D

**Pull request merged**
