### PR TITLE
fix: compilation error when including WorldPosition

### PR DESCRIPTION
**Pull request by poirierlouis**
Vector4 is not included while used in constructor of WorldPosition.

### CODE REVIEW

**Review by psiberx — DISMISSED** [review]

**Comment by psiberx** [comment]
What about Vector3?

**Comment by poirierlouis** [comment]
Good question, I don't know why, but no compilation error regarding Vector3. Even if it is not directly / indirectly imported afaik, like Vector4.

**Comment by psiberx** [comment]
It depends on your other includes. To make it work in any context, you should add Vector3 as well.

**Comment by poirierlouis** [comment]
Alright, it is done.

**Review by psiberx — APPROVED** [review]

**Pull request merged**
